@apiURL = http://localhost:8080/users

GET {{{{apiURL}}}}


###

POST {{apiURL}}/register
Content-Type: application/json

{
    "name": "test",
    "lastname": "testing",
    "email": "testing@testtt.com",
    "password": "TESTtestTEST"
}

###

POST {{apiURL}}/login
Content-Type: application/json

{
    "email": "testing@testt.com",
    "password": "TESTtestTEST"
}
